apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-springboot-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: my-springboot-app
        image: 211223789150.dkr.ecr.us-east-2.amazonaws.com/my-docker-repo
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-app-svc
spec:
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer
